const API_BASE='';
const app=document.querySelector('#app');
const user={department_id:'生产部',role:'employee',allowed_departments:['生产部']};
const safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={conversationId:'demo',documents:[],evaluation:null};
const pageHead=(k,t,d,action='')=>`<div class="page-head"><div><div class="kicker">${k}</div><h1>${t}</h1><p>${d}</p></div>${action?`<button class="primary" data-action="${action}">${action}</button>`:''}</div>`;
async function api(path,options={}){const response=await fetch(`${API_BASE}${path}`,options);let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body.detail||`请求失败（${response.status}）`);return body}
function empty(text){return `<div class="notice">${text}</div>`}
function agent(){app.innerHTML=pageHead('AGENT WORKSPACE','可信知识问答','只回答已授权资料中的内容，并保留可追溯引用。')+`<section class="panel workspace"><aside class="task-rail"><h3>会话与任务</h3><button class="task active" data-action="current">设备维修支持<small>当前会话 · 生产部</small></button><button class="task" data-action="new-chat">新建会话<small>开始新的问题</small></button><h3 style="margin-top:28px">快捷任务</h3><button class="task" data-action="table">▤ 整理成表格<small>对最近回答进行整理</small></button><button class="task" data-action="training">＋ 生成培训材料<small>需先确认范围</small></button></aside><section class="chat"><div class="chat-head"><div><strong>设备维修支持</strong><div class="meta">知识范围：生产部 · 权限过滤已启用</div></div><span class="status">● 服务在线</span></div><div class="messages" id="messages">${empty('请输入问题开始对话。系统会在答案下方显示实际引用。')}</div><form class="composer" id="composer"><input aria-label="输入问题" placeholder="例如：E-204 点检时第一步是什么？"/><button class="primary">发送</button></form></section><aside class="detail empty" id="detail"><div><div style="font-size:30px">⌁</div><strong>点击引用查看依据</strong><p>原文、页码、版本和权限信息将在这里展示。</p></div></aside></section>`;document.querySelector('#composer').onsubmit=sendQuestion}
async function sendQuestion(event){event.preventDefault();const input=event.target.querySelector('input'),question=input.value.trim();if(!question)return;const messages=document.querySelector('#messages');messages.insertAdjacentHTML('beforeend',`<div class="message user">${safe(question)}</div>`);input.value='';const pending=document.createElement('div');pending.className='message agent';pending.innerHTML='<span class="answer-label">检索中…</span><p>正在查询已授权知识库。</p>';messages.append(pending);try{const result=await api(`/api/projects/demo/conversations/${state.conversationId}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:question,user})});pending.innerHTML=`<span class="answer-label">${safe(result.status==='ANSWERED'?'已完成检索':result.status==='REFUSED'?'依据不足 · 主动拒答':'服务异常')}</span><p>${safe(result.answer)}</p>`+(result.citations||[]).map(citation=>`<button class="citation">↗ ${safe(citation.document_filename)} · p.${citation.page}</button>`).join('');pending.querySelectorAll('.citation').forEach((button,index)=>button.onclick=()=>showCitation(result.citations[index]))}catch(error){pending.innerHTML=`<span class="answer-label">请求失败</span><p>${safe(error.message)}</p>`}messages.scrollTop=messages.scrollHeight}
function showCitation(citation){const detail=document.querySelector('#detail');detail.className='detail';detail.innerHTML=`<h3>引用详情</h3><div class="doc-title">${safe(citation.document_filename)}</div><div class="meta">第 ${citation.page} 页 · 已授权</div><div class="quote">“${safe(citation.text)}”</div>`}
async function overview(){app.innerHTML=pageHead('PROJECT OVERVIEW','项目概览','查看当前真实服务状态和 P0 交付边界。')+`<div class="cards"><div class="panel metric"><span class="label">核心问答</span><strong>已接通</strong><em>同源 API</em></div><div class="panel metric"><span class="label">文档上传</span><strong>可用</strong><em>PDF / DOCX / TXT</em></div><div class="panel metric"><span class="label">批量评测</span><strong>可用</strong><em>40 条黄金题</em></div><div class="panel metric"><span class="label">权限模式</span><strong>演示角色</strong><em>生产部员工</em></div></div><div class="grid2"><section class="panel section"><h2>服务状态</h2><div id="service-status">正在检查后端…</div></section><section class="panel section"><h2>当前交付边界</h2>${empty('P0 已完成：问答、引用、拒答、上传、评测。登录、真实反馈队列和原文预览仍属于后续阶段。')}</section></div>`;try{const health=await api('/health');document.querySelector('#service-status').innerHTML=Object.entries(health).map(([key,value])=>`<div class="notice"><strong>${safe(key)}</strong><span class="tag">${safe(value)}</span></div>`).join('')}catch(error){document.querySelector('#service-status').innerHTML=empty(`后端不可用：${safe(error.message)}`)}}
async function loadDocuments(){state.documents=await api('/api/projects/demo/documents');return state.documents}
async function knowledge(){app.innerHTML=pageHead('KNOWLEDGE BASE','知识库','查看真实入库文档。上传后页面会刷新处理状态。','上传文件')+`<section class="panel section"><div id="document-status">正在加载文档…</div><div id="document-table"></div></section>`;try{await renderDocuments()}catch(error){document.querySelector('#document-status').innerHTML=empty(`加载失败：${safe(error.message)}`)}}
async function renderDocuments(){const documents=await loadDocuments();document.querySelector('#document-status').textContent=`已加载 ${documents.length} 份当前可见文档`;document.querySelector('#document-table').innerHTML=documents.length?`<table class="table"><thead><tr><th>文件名</th><th>部门</th><th>状态</th><th>ID</th></tr></thead><tbody>${documents.map(doc=>`<tr><td><strong>${safe(doc.filename)}</strong></td><td>${safe(doc.department_id)}</td><td><span class="tag ${doc.status==='FAILED'?'warn':''}">${safe(doc.status)}</span></td><td class="meta">${safe(doc.id.slice(0,8))}</td></tr>`).join('')}</tbody></table>`:empty('暂无已入库文档，请点击“上传文件”。')}
async function evaluation(){app.innerHTML=pageHead('EVALUATION','评测中心','运行真实黄金测试集，结果会显示在本页面。','运行评测')+`<div id="evaluation-result">${empty('尚未运行本次评测。')}</div>`;if(state.evaluation)renderEvaluation(state.evaluation)}
function renderEvaluation(result){const metrics=result.metrics||{};document.querySelector('#evaluation-result').innerHTML=`<div class="cards">${[['答案准确率',metrics.answer_accuracy],['引用片段精度',metrics.chunk_precision],['页码命中率',metrics.page_hit_rate],['拒答准确率',metrics.refusal_accuracy]].map(([label,value])=>`<div class="panel metric"><span class="label">${label}</span><strong>${typeof value==='number'?`${Math.round(value*100)}%`:safe(value)}</strong></div>`).join('')}</div><section class="panel section" style="margin-top:18px"><h2>逐题结果（${result.results?.length||0} 条）</h2>${(result.results||[]).slice(0,10).map(item=>`<div class="notice"><strong>${safe(item.id)} · ${safe(item.answer_correct?'正确':'需复核')}</strong><p>${safe(item.question)}</p><p>${safe(item.answer||'无答案')}</p></div>`).join('')}</section>`}
function risks(){app.innerHTML=pageHead('FEEDBACK & RISK','反馈与风险','展示当前可追溯的风险边界，不把静态样例冒充真实工单。','查看处理队列')+`<section class="panel section"><h2>当前已知限制</h2>${empty('暂无独立的反馈列表 API；当前页面只展示风险说明，不会伪造处理状态。')}<div id="risk-details"></div></section>`}
const pages={agent,overview,knowledge,evaluation,risks};
async function show(page){document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.page===page));await pages[page]()}
document.querySelectorAll('.nav-item').forEach(item=>item.onclick=()=>show(item.dataset.page));
document.addEventListener('click',async event=>{const button=event.target.closest('button[data-action]');if(!button)return;const action=button.dataset.action;if(action==='new-chat'){state.conversationId='demo-'+Date.now();show('agent');return}if(action==='table'||action==='training'){const target=document.querySelector('#messages');if(target)target.insertAdjacentHTML('beforeend',`<div class="message agent"><span class="answer-label">任务已创建</span><p>${action==='table'?'整理成表格':'生成培训材料'}需要确认资料范围后执行。</p></div>`);return}if(action==='上传文件'){const input=document.createElement('input');input.type='file';input.accept='.pdf,.docx,.txt';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;button.disabled=true;button.textContent='上传中…';const body=new FormData();body.append('file',file);try{const result=await api(`/api/projects/demo/documents?department_id=${encodeURIComponent('生产部')}`,{method:'POST',body});await renderDocuments();document.querySelector('#document-status').textContent=`上传成功：${result.message||file.name}`}catch(error){document.querySelector('#document-status').innerHTML=empty(`上传失败：${safe(error.message)}`)}finally{button.disabled=false;button.textContent='上传文件'}};input.click();return}if(action==='运行评测'){button.disabled=true;button.textContent='评测中…';try{state.evaluation=await api('/api/projects/demo/evaluations/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({limit:40,user})});renderEvaluation(state.evaluation)}catch(error){document.querySelector('#evaluation-result').innerHTML=empty(`评测失败：${safe(error.message)}`)}finally{button.disabled=false;button.textContent='运行评测'}return}if(action==='查看处理队列'){document.querySelector('#risk-details').innerHTML=empty('处理队列 API 尚未实现，本页面不会伪造“已处理”结果.')}});
show('agent');
