const docs=[{name:'设备安全操作规程_v3.pdf',meta:'第 12 页 · 安全规程 · 生产部',text:'进行点检或清扫前，必须关闭主电源并确认指示灯熄灭。'}];
const safe=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const app=document.querySelector('#app');
const pageHead=(k,t,d,action='')=>`<div class="page-head"><div><div class="kicker">${k}</div><h1>${t}</h1><p>${d}</p></div>${action?`<button class="primary">${action}</button>`:''}</div>`;
function agent(){app.innerHTML=pageHead('AGENT WORKSPACE','可信知识问答','基于已授权的企业资料回答，所有结论都保留可追溯来源。')+`<section class="panel workspace"><aside class="task-rail"><h3>会话与任务</h3><button class="task active"><b>设备维修支持</b><small>刚刚 · 2 条消息</small></button><button class="task"><b>新建会话</b><small>从一个问题开始</small></button><h3 style="margin-top:28px">快捷任务</h3><button class="task"><b>▤ 整理成表格</b><small>步骤、负责人、风险</small></button><button class="task"><b>＋ 生成培训材料</b><small>需生成前确认范围</small></button></aside><section class="chat"><div class="chat-head"><div><strong>设备维修支持</strong><div class="meta">知识范围：生产部 · 已完成权限过滤</div></div><span class="status">● 在线</span></div><div class="messages"><div class="message user">E-204 错误代码出现时，清扫设备前需要做什么？</div><div class="message agent"><span class="answer-label">有充分依据 · 日文资料</span><p>清扫设备前，必须先关闭主电源，并确认指示灯已经熄灭。针对 E-204，当前知识库未提供额外的复位步骤，建议由现场负责人按维修规程确认。</p><div class="citations"><button class="citation" data-cite="0">↗ 设备安全操作规程_v3.pdf · p.12</button></div><div class="risk">⚠ 高风险操作：请在执行前由现场负责人确认断电状态。</div></div><div class="message user">帮我确认一下知识库里有没有 E-999 的处理方法。</div><div class="message agent"><span class="answer-label">依据不足 · 主动拒答</span><p>根据当前已授权知识库，无法确认 E-999 的处理方法。请补充对应设备型号或上传错误代码表，我不会基于常识编造维修步骤。</p></div></div><form class="composer"><input aria-label="输入问题" placeholder="继续提问，例如：把刚才步骤整理成表格"/><button class="primary">发送</button></form></section><aside class="detail empty" id="detail"><div><div style="font-size:30px">⌁</div><strong>点击引用查看依据</strong><p>原文、页码、版本和权限信息将在这里展示。</p></div></aside></section>`;document.querySelectorAll('.citation').forEach(b=>b.onclick=()=>{const d=docs[b.dataset.cite];document.querySelector('#detail').className='detail';document.querySelector('#detail').innerHTML=`<h3>引用详情</h3><div class="doc-title">${d.name}</div><div class="meta">${d.meta} · 已授权</div><div class="quote">“${d.text}”</div><button class="primary" style="margin-top:18px">打开原文</button>`});document.querySelector('.composer').onsubmit=e=>{e.preventDefault();const i=e.target.querySelector('input');if(!i.value.trim())return;document.querySelector('.messages').insertAdjacentHTML('beforeend',`<div class="message user">${safe(i.value)}</div><div class="message agent"><span class="answer-label">演示模式 · 等待知识库检索</span><p>已记录问题。真实环境将先执行权限过滤与混合检索，再返回带引用的回答。</p></div>`);i.value=''} }
function overview(){app.innerHTML=pageHead('PROJECT OVERVIEW','项目概览','日本制造企业设备维修知识助手 · P0 可信问答闭环','进入 Agent 工作台')+`<div class="cards"><div class="panel metric"><span class="label">周期活跃用户</span><strong>24</strong><em>↑ 12% 本周</em></div><div class="panel metric"><span class="label">有效提问</span><strong>186</strong><em>↑ 28% 本周</em></div><div class="panel metric"><span class="label">引用正确率</span><strong>92%</strong><em>目标 ≥ 90%</em></div><div class="panel metric"><span class="label">主动拒答率</span><strong>88%</strong><em>目标 ≥ 85%</em></div></div><div class="grid2"><section class="panel section"><h2>能力交付进度</h2>${[['P0 · 可信问答闭环',72,'进行中'],['P1 · 企业内容生产',18,'规划中'],['P2 · 管理洞察自动化',4,'未开始']].map(x=>`<div class="notice"><strong>${x[0]} <span class="meta" style="float:right">${x[2]}</span></strong><div class="bar"><i style="width:${x[1]}%"></i></div><p style="margin-top:6px">${x[1]}% · 权限、引用、拒答和评测优先</p></div>`).join('')}</section><section class="panel section"><h2>最近质量信号</h2><div class="notice"><strong>错误代码召回率 <span class="tag">96%</span></strong><p>混合检索对型号和术语表现稳定</p></div><div class="notice"><strong>待人工复核 <span class="tag warn">3 份</span></strong><p>低 OCR 置信度文档不会参与检索</p></div><div class="notice"><strong>权限越权成功率 <span class="tag">0%</span></strong><p>检索层已启用部门过滤演示</p></div></section></div>`}
function knowledge(){app.innerHTML=pageHead('KNOWLEDGE BASE','知识库','文档先解析、分块、索引；失败或待复核内容不参与默认检索。','上传文件')+`<section class="panel section"><div class="panel-head"><h3>企业文档 <span class="badge">12</span></h3></div><table class="table"><thead><tr><th>文件名</th><th>版本</th><th>所属部门</th><th>处理状态</th><th>更新时间</th></tr></thead><tbody>${[['设备安全操作规程_v3.pdf','v3.0','生产部','已完成'],['故障代码与处理方法.pdf','v2.1','维修部','索引中'],['新人点检培训手册.docx','v1.2','人事部','需人工复核'],['客户设备 FAQ.txt','v1.0','客服部','已完成']].map(x=>`<tr><td><strong>${x[0]}</strong></td><td>${x[1]}</td><td>${x[2]}</td><td><span class="tag ${x[3]==='需人工复核'?'warn':''}">${x[3]}</span></td><td class="meta">2026-09-02</td></tr>`).join('')}</tbody></table></section>`}
function evaluation(){app.innerHTML=pageHead('EVALUATION','评测中心','用黄金测试集验证答案、引用与拒答，不让演示数据冒充生产指标。','运行评测')+`<div class="cards"><div class="panel metric"><span class="label">答案准确率</span><strong>84%</strong><em>目标 ≥ 80%</em></div><div class="panel metric"><span class="label">关键点覆盖率</span><strong>89%</strong><em>目标 ≥ 85%</em></div><div class="panel metric"><span class="label">引用正确率</span><strong>92%</strong><em>目标 ≥ 90%</em></div><div class="panel metric"><span class="label">平均响应时间</span><strong>2.8s</strong><em>目标 ≤ 10s</em></div></div><section class="panel section" style="margin-top:18px"><h2>最近一次运行 · 40 条测试问题</h2><table class="table"><tr><th>失败归因</th><th>数量</th><th>状态</th></tr><tr><td>检索没有召回正确片段</td><td>3</td><td><span class="tag warn">待分析</span></td></tr><tr><td>应该拒答但模型继续编造</td><td>1</td><td><span class="tag">已修复</span></td></tr><tr><td>引用与结论不一致</td><td>2</td><td><span class="tag warn">待分析</span></td></tr></table></section>`}
function risks(){app.innerHTML=pageHead('FEEDBACK & RISK','反馈与风险','把用户纠正和高风险场景纳入可追溯的质量闭环。','查看处理队列')+`<section class="panel section"><h2>待处理事项</h2><div class="notice"><strong><span class="tag warn">高风险</span> E-204 回答需要现场确认</strong><p>来源：设备维修支持 · 负责人：业务专家 · 记录于 10 分钟前</p></div><div class="notice"><strong><span class="tag">纠正</span> “复位步骤”缺少对应版本引用</strong><p>来源：维修部 · 状态：待复核</p></div><div class="notice"><strong><span class="tag">反馈</span> 用户希望增加中文辅助解释</strong><p>来源：生产部 · 状态：已记录</p></div></section>`}
const pages={agent,overview,knowledge,evaluation,risks};function show(p){pages[p]();document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===p))}document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>show(n.dataset.page));show('agent');

// ponytail: mock data keeps the prototype runnable without inventing backend contracts; replace with API calls when FastAPI is available.
function demo(){console.assert(document.querySelector('.answer-label'),'可信回答已渲染');console.assert(document.querySelector('.citation'),'引用入口已渲染');console.assert(document.body.innerText.includes('主动拒答'),'拒答状态已渲染')}demo();
